# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      #https://github.com/SpicyPizza/create-envfile
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_AUTHORIZATION_KEY: ${{ secrets.AUTHORIZATION_KEY }}
        envkey_BASE_URL: "https://sandbox.safaricom.co.ke"
        envkey_CONFIRMATION_URL: "https://soluhisho.com/confirmation"
        envkey_RESPONSE_TYPE: "Completed"
        envkey_SHORT_CODE: "123456"
        envkey_VALIDATION_URL: "https://soluhisho.com/validation"
        

    - name: Test with pytest
      run: |
        pytest -vvv
